#include <Arduino.h>
#include "ui/lv_setup.h"
#include "ui/ui.h"
#include "pin_config.h"
#include "time_func.h"
#include "wifi_func.h"
#include "ota_update.h"


void setup()
{
  connect();   // Connect to WiFi
  time_init(); // Initialize time and date from compiler
  lv_begin();  // Initialize lvgl with display and touch
  ui_init();   // Initialize UI generated by Square Line
}
int start = millis();
void loop()
{
  lv_handler();  // Update UI
  update_time(); // Update time and date on UI
  if (millis() - start > 60000)
  {
    checkForUpdate(); // Check for new firmware update
    start = millis();
  }
}